### ISSUE TITLE
any method to catch/get error output

### ISSUE THREAD

**Issue by mitechie** [qoda/python-wkhtmltopdf#1]
I'm working on wrapping this and if there's an issue writing the output (say the output directory doesn't exist) I'm not finding a way to catch the output. 

I can see it ouput to stdout, but there's no method after I call .render() to get any of it.

Sample output

```
wkhtmltopdf --enable-plugins --redirect-delay 1 --orientation Landscape --dpi 100 "http://google.com" "/home/rharding/tmp/pdf/google.pdf" >> /tmp/wkhtp.log
Loading pages (1/5)
QPainter::begin(): Returned false============================] 100%
Error: Unable to write to destination          
```

Is there any way I'm missing to catch that Error: line? Possible to do it in the wrapper?

**Comment by Ontseason** [comment]
have you fixed the bug? I have the same problem
