### ISSUE TITLE
Spelling error in pypi documentation 

### ISSUE THREAD

**Issue by JoeJasinski** [qoda/python-wkhtmltopdf#6]
The usage documentation on pypi has a class name PWKhtmlToPd with a capital "H" whereas the actual class name in github has a lower case "h".  

http://pypi.python.org/pypi?:action=display&name=wkhtmltopdf&version=0.1

vs. 

https://github.com/qoda/python-wkhtmltopdf/blob/master/wkhtmltopdf/main.py#L113

**Comment by qoda** [comment]
No longer in development
